apiVersion: v1
kind: ServiceAccount
metadata:
  name: green-k8s-descheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: green-k8s-descheduler-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: green-k8s-descheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-k8s-descheduler-config
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-k8s-descheduler
  namespace: kube-system
  labels:
    app: green-k8s-descheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-k8s-descheduler
  template:
    metadata:
      labels:
        app: green-k8s-descheduler
    spec:
      serviceAccountName: green-k8s-descheduler
      volumes:
      - name: green-k8s-descheduler-config
        configMap:
          name: green-k8s-descheduler-config
      containers:
      - name: green-k8s-descheduler
        image: timokraus/green-k8s-descheduler
        imagePullPolicy: Always
        volumeMounts:
        - name: green-k8s-descheduler-config
          mountPath: /green-k8s-descheduler
